import datetime
import csv
import statistics
import matplotlib.pyplot as plt

# Reading the IPO Lockup csv will all our metadata and the ticker names
Stocklist = 'Financial Data/ipo_metadata.csv'

# Because we are using a lot of moving parts (yfinance library, matplot, statistics, incomplete Financial Data) there is a high chance of errors in our codebase.
# Because of this, it is wise to implement an Error Logging system in order to pinpoint what has gone wrong in our code and why. Errors being spelled out in plain english instead of difficult-to-read code can allow us to pinpoint problems and debug more efficiently.

Error_Logs = 'error_logs.csv'

error_types = [
    "Graph Creation",
    "Volatility Calculation",
    "Similarity Scores",
    "SPCX Comparison Data",
    "Missing Historical Outcome",
    "Not enough days in comparison window"
]

function_names = [
    "save_volatility_chart",
    "volatility",
    "user_interface_controller",
    "scoring_function",
    "prediction_function",
    "date_window"
]

errors = {
    "volatility_chart": {
        "Function Name": function_names[0],
        "Error Type": error_types[0],
        "Message": "Volatility chart cannot be created because no windows were provided",
        "Severity": "Low" # Some errors are not fatal, thus we want to categorize them on a "Low / Mid / High" severity basis so we can prioritize adequately.
    },
    "volatility_daily_returns": {
        "Function Name": function_names[1],
        "Error Type": error_types[1],
        "Message": "Volatility cannot be calculated with less than 2 entries",
        "Severity": "High"
    },
    "similarity_scores": {
        "Function Name": function_names[2],
        "Error Type": error_types[2],
        "Message": "Similarity scores cannot be appended due to 0 entries in 'similarity_scores'",
        "Severity": "High"
    },
    "invalid_comparison": {
        "Function Name": function_names[3],
        "Error Type": error_types[3],
        "Message": "Invalid comparison SpaceX value (None), skipping record",
        "Severity": "Mid"
    },
    "empty_historical_outcome": {
        "Function Name": function_names[4],
        "Error Type": error_types[4],
        "Message": "Empty historical return, cannot run prediction function on this specific value",
        "Severity": "Mid"
    },
    "thirty_day_window_length": { # SpaceX releases its tranches very close to one another, so we might need to either scrap this error or make a helper function that specifically logs the length of all the tickers except SpaceX
        "Function Name": function_names[5],
        "Error Type": error_types[5],
        "Message": "Not enough days in company tranche window",
        "Severity": "Low" # As long as we have sufficient Financial Data it does not matter if it's been less than a month since a company's lockup. Thus, severity for this is "Low". The real issue would be if yahoo finance is not generating enough existing Financial Data
    }
}

# Error logging helper function, intakes the dictionary key an adds the errors to error_logs.csv
def error_logging(error_key):
    if error_key not in errors: # Conditional to check the valid key exists.
        return
    with open(Error_Logs, 'a') as csvfile:
        append = csv.writer(csvfile)
        timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        error_dict = errors[error_key]

        var1 = error_dict["Function Name"]
        var2 = error_dict["Error Type"]
        var3 = error_dict["Message"]
        var4 = error_dict["Severity"]

        append.writerow([timestamp, var1, var2, var3, var4])


def read_ipo_lockups():
    with open('Financial Data/ipo_metadata.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        lockups = []
        for row in reader:
            lockups.append(row)
    return lockups

# read_ipo_lockups()

# Reading the companies csv generated by tickers_pipeline

def read_companies():
    with open('Financial Data/companies.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        companies = []
        for row in reader:
            companies.append(row)
    return companies

# Functions that called what were returned by the read functions

# companies = read_companies()
# lockups = read_ipo_lockups()

# Filtering the rows to return all tickers with the same name Ex: "META" into an accessible format allowing us to score them easier

def company_filter(ticker, companies):
    matching_companies = []
    for company in companies:
        if company['ticker'] == ticker:
            matching_companies.append(company)
    return matching_companies

# Same exact thing but instead filtering lockups to make all the metadata in ipo_metadata.csv accessible to be called

def lockup_filter(ticker, lockups):
    matching_lockups = []
    for lockup in lockups:
        if lockup['ticker'] == ticker:
            matching_lockups.append(lockup)
    return matching_lockups

# Filtering the IPO lockup dates to only pull Financial Data from the relevant tranches and specific periods for scoring

def date_window(matching_lockups, matching_companies):
    all_windows = []

    sorted_companies = sorted(
        matching_companies,
        key=lambda company: datetime.datetime.strptime(company['date'], "%Y-%m-%d"))
    for lockup in matching_lockups:
        lockup_date = lockup['lockup_date']
        lockup_datetime = datetime.datetime.strptime(lockup_date, "%Y-%m-%d")
        date_window_list = []
        for company in sorted_companies:
            company_date = company['date']
            company_datetime = datetime.datetime.strptime(company_date, "%Y-%m-%d")
            if company_datetime < lockup_datetime:
                date_window_list.append(company)
        thirty_day_window = date_window_list[-30:]
        window_record = {
            "lockup": lockup,
            "trading_window": thirty_day_window
        }
        # if len(thirty_day_window) < 30: # Right now, some yfinance Financial Data is missing from companies.csv (likely due to me not having a paid plan). If we cannot supplement this Financial Data using a substitute of yfinance, we can get rid of this error and conditional
        #     error_logging(errors[""])
        #     print("Incomplete tranche, skipping window..")
        #     continue

        all_windows.append(window_record)
    return all_windows

def thirty_day_momentum(date_windows):
    momentum_results = []
    for window_record in date_windows:
        trading_window = window_record["trading_window"]
        first_close = float(trading_window[0]["close"])
        last_close = float(trading_window[-1]["close"])
        momentum = (last_close / first_close) - 1
        momentum_results.append(momentum)
    return momentum_results

# This is the function we use to calculate the volatility of the stock

# Helper function in order to allow us to print the results
def save_volatility_chart(date_windows, volatility_results):
    if len(date_windows) == 0:
        error_logging("volatility_chart")
        raise ValueError("Volatility chart cannot be created because no windows were provided")

    tranche_labels = []

    for window_record in date_windows:
        tranche = window_record["lockup"]["tranche"]
        tranche_labels.append(f"Tranche {tranche}")
    ticker = date_windows[0]["lockup"]["ticker"]
    plt.figure(figsize=(8, 5))
    plt.bar(tranche_labels, volatility_results)
    plt.title(f"{ticker} 30-Day Pre-Lockup Volatility")
    plt.xlabel("Lockup Tranche")
    plt.ylabel("Standard Deviation")
    plt.tight_layout()
    file_path = f"Financial Data/{ticker}_volatility.png"
    plt.savefig(file_path)
    plt.close()
    return file_path

def volatility(date_window):
    volatility_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        daily_returns = []
        for day_index in range(1, len(trading_window)): # This inner loop is meant to find the exact day-to-day close and previous close. We cannot use basic indexing because volatility needs to compare everything to the day before it
            current_close = float(trading_window[day_index]["close"])
            previous_close = float(trading_window[day_index - 1]["close"])

            daily_return_calculation = current_close / previous_close - 1

            daily_returns.append(daily_return_calculation)
        # End of the inner loop, the purpose was to simply calculate the daily return percentage and add it to daily_returns for each company
        if len(daily_returns) < 2:
            error_logging("volatility_chart")
            raise ValueError("Volatility cannot be calculated with less than 2 entries")

        standard_deviation_volatility = statistics.stdev(daily_returns)
        volatility_results.append(standard_deviation_volatility)

    save_volatility_chart(date_window, volatility_results)
    return volatility_results

# This next function is meant to find the daily trading volume for each stock and tranche. This function allows us to calculate shares unlock with average trading volume, allowing us to see how much the shares unlocked affects the trading volume
def average_trading_volume(date_window):
    trading_volume_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        daily_volume = []
        for day_index in range(0, len(trading_window)): # Inner loop is meant to iterate to each individual company day and return the day-to-day results from companies.csv
            day_volume = float(trading_window[day_index]["volume"])
            daily_volume.append(day_volume)
        average_daily_volume = statistics.mean(daily_volume)
        trading_volume_results.append(average_daily_volume)
    return trading_volume_results

# A usable variable that allows us to access the output from average trading volume

def unlock_to_volume_ratio(date_window, avg_volume):
    ratio_results = []
    for index, window_record in enumerate(date_window):
        # Metadata uses millions; Yahoo volume uses individual shares.
        shares_unlocked = (
                float(window_record["lockup"]["shares_unlocked"]) * 1_000_000
        )
        matching_average_volume = avg_volume[index]
        if matching_average_volume == 0:
            ratio_results.append(None)
            continue
        u_to_v_ratio = shares_unlocked / matching_average_volume
        ratio_results.append(u_to_v_ratio)
    return ratio_results

# Now we are moving to an outcome, we are not comparing historical return to similarity, we are measuring an outcome determine if the SpaceX stock is bullish or bearish based on how past post-lockup returns happened.
# The question we are trying to answer is "What happened to the stock after its original lockup expiration?"

def historical_return(date_window, filtered_companies):
    historical_results = []

    sorted_companies = sorted(
        filtered_companies,
        key=lambda company: datetime.datetime.strptime(company["date"], "%Y-%m-%d"))
    for window_record in date_window:
        lockup_date = window_record["lockup"]["lockup_date"]
        lockup_datetime = datetime.datetime.strptime(lockup_date, "%Y-%m-%d")
        post_lockup_rows = []
        for company in sorted_companies:
            company_datetime = datetime.datetime.strptime(company["date"], "%Y-%m-%d")
            if company_datetime >= lockup_datetime:
                post_lockup_rows.append(company)
        if len(post_lockup_rows) >= 21:
            starting_close = float(post_lockup_rows[0]["close"])
            ending_close = float(post_lockup_rows[20]["close"])

            twenty_day_return = (ending_close / starting_close) - 1
            historical_results.append(twenty_day_return)
        else:
            historical_results.append(None)
    return historical_results

def market_cap_metric(date_window):
    market_cap_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        latest_market_cap = None
        for company in reversed(trading_window):
            if company["market_cap"]:
                latest_market_cap = float(company["market_cap"])
                break
        market_cap_results.append(latest_market_cap)
    return market_cap_results


def price_to_sales(date_window):
    price_to_sales_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        price_to_sales_ratio = None
        for company in reversed(trading_window):
            if company["market_cap"] and company["revenue"] and company["period"] == "TTM":
                market_cap = float(company["market_cap"])
                ttm_revenue = float(company["revenue"])

                if ttm_revenue != 0:
                    price_to_sales_ratio = market_cap / ttm_revenue
                    break
        price_to_sales_results.append(price_to_sales_ratio)
    return price_to_sales_results

# Function for calculating the company's revenue growth

def revenue_growth(date_window, filtered_companies):
    revenue_growth_results = []
    sorted_companies = sorted(
        filtered_companies,
        key=lambda company: datetime.datetime.strptime(company["date"], "%Y-%m-%d"))
    for window_record in date_window:
        lockup_date = window_record["lockup"]["lockup_date"]
        lockup_datetime = datetime.datetime.strptime(lockup_date, "%Y-%m-%d")
        revenue_updates = []
        previous_revenue = None
        for company in sorted_companies:
            company_datetime = datetime.datetime.strptime(company["date"], "%Y-%m-%d")
            if company_datetime >= lockup_datetime:
                break
            if company["revenue"] and company["period"] == "TTM":
                current_revenue = float(company["revenue"])
                if current_revenue != previous_revenue:
                    revenue_updates.append(current_revenue)
                    previous_revenue = current_revenue
        if len(revenue_updates) >= 5:
            current_ttm_revenue = revenue_updates[-1]
            prior_year_ttm_revenue = revenue_updates[-5]
            if prior_year_ttm_revenue != 0:
                growth = (current_ttm_revenue / prior_year_ttm_revenue) - 1
                revenue_growth_results.append(growth)
            else:
                revenue_growth_results.append(None)
        else:
            revenue_growth_results.append(None)
    return revenue_growth_results

# This defines the profile for each of the tickers that we will use to score against SpaceX. The profile includes everything that we will use to compare our companies

def profile_combination_helper(date_windows, momentum_results, volatility_results, avg_volume, ratio_results, historical_results, market_cap_metrics, price_to_sale, revenue_growth_function):
    finished_profiles = []
    for index, window in enumerate(date_windows):
        tranche_profile = {
            "ticker": window["lockup"]["ticker"],
            "tranche": window["lockup"]["tranche"],
            "lockup_date": window["lockup"]["lockup_date"],
            "shares_unlocked": window["lockup"]["shares_unlocked"],
            "momentum": momentum_results[index],
            "volatility": volatility_results[index],
            "average_volume": avg_volume[index],
            "unlock_to_volume": ratio_results[index],
            "historical_return": historical_results[index],
            "market_cap": market_cap_metrics[index],
            "price_to_sales": price_to_sale[index],
            "revenue_growth": revenue_growth_function[index]
        }
        finished_profiles.append(tranche_profile)
    return finished_profiles

# Flow control function, meant to control the sequence of all of our Financial Data gathering and calculation functions

def analyze_ticker(ticker):
    filtered_lockups = lockup_filter(ticker, lockups)
    filtered_companies = company_filter(ticker, companies)
    date_windows = date_window(filtered_lockups, filtered_companies)
    momentum_results = thirty_day_momentum(date_windows)
    volatility_results = volatility(date_windows)
    avg_volume = average_trading_volume(date_windows)
    ratio_results = unlock_to_volume_ratio(date_windows, avg_volume)
    historical_results = historical_return(date_windows, filtered_companies)
    market_cap_metrics = market_cap_metric(date_windows)
    price_to_sale = price_to_sales(date_windows)
    revenue_growth_function = revenue_growth(date_windows, filtered_companies)
    finished_profiles = profile_combination_helper(date_windows, momentum_results, volatility_results, avg_volume, ratio_results, historical_results, market_cap_metrics, price_to_sale, revenue_growth_function)
    return finished_profiles

# We are using the same scoring functions we used for the other companies on SPACEX
# We have to do this by passing SPCX through the function argument in the place of ticker

# spacex_companies_filter = company_filter("SPCX", companies)
# spacex_lockup_filter = lockup_filter("SPCX", lockups)

# spacex_date_window = date_window(
#     spacex_lockup_filter,
#     spacex_companies_filter
# )

# spacex_avg_volume = average_trading_volume(spacex_date_window)
# spacex_momentum = thirty_day_momentum(spacex_date_window)
# spacex_volatility = volatility(spacex_date_window)
# spacex_ratio = unlock_to_volume_ratio(spacex_date_window, spacex_avg_volume)
# spacex_market_cap = market_cap_metric(spacex_date_window)
# spacex_price_to_sales = price_to_sales(spacex_date_window)
# spacex_revenue_growth = revenue_growth(spacex_date_window, spacex_companies_filter)

# Next, we create global SpaceX variable in order to process the SpaceX Financial Data and define what we are actually scoring.

# THE GLOBAL VARIABLE WILL FEATURE A ONE-TIME SNAPSHOT WITH DATA AS OF 9/10/2026, THE PROFILE DOES NOT UPDATE UPON EACH RUN TIME

SPACEX_PROFILE = []

# for index, window in enumerate(spacex_date_window):
#     spacex_profile = {
#         "ticker": "SPCX",
#         "tranche": window["lockup"]["tranche"],
#         "momentum": spacex_momentum[index],
#         "volatility": spacex_volatility[index],
#         "unlock_to_volume": spacex_ratio[index],
#         "market_cap": spacex_market_cap[index],
#         "price_to_sales": spacex_price_to_sales[index],
#         "revenue_growth": spacex_revenue_growth[index]
#     }
#     SPACEX_PROFILE.append(spacex_profile)

# Next, we move onto building the similarity scoring engine, the part of engine.py meant to compare SpaceX to the other companies and assess how the stock will perform in its next tranche.

# The function we are making intakes SPACEX_PROFILE as a parameter, later on when we eventually edit IPO-LENS to feature other IPOs like Anthropic & AI, we can call the function but pass something like "ANTHROPIC_PROFILE" through it instead.

def analyze_spacex_data(SPACEX_PROFILE, finished_profiles):
    comparison_data = [] # Meant to hold all the comparisons and return them
    for spacex_profile in SPACEX_PROFILE:
        for historical_profile in finished_profiles:
            similarity_profiles = {
                "spacex_tranche": spacex_profile["tranche"],
                "historical_ticker": historical_profile["ticker"],
                "historical_tranche": historical_profile["tranche"],
                "historical_return": historical_profile["historical_return"],
                "momentum": (spacex_profile["momentum"], historical_profile["momentum"]),
                "volatility": (spacex_profile["volatility"], historical_profile["volatility"]),
                "unlock_to_volume": (spacex_profile["unlock_to_volume"], historical_profile["unlock_to_volume"]),
                "market_cap": (spacex_profile["market_cap"], historical_profile["market_cap"]),
                "price_to_sales": (spacex_profile["price_to_sales"], historical_profile["price_to_sales"]),
                "revenue_growth": (spacex_profile["revenue_growth"], historical_profile["revenue_growth"])
            }
            comparison_data.append(similarity_profiles)

    return comparison_data

# Meant to score the similarity of other stocks to SpaceX using a mathematical engine, as well as built-in python averaging and mathematical functions
# Essentially, the function takes a parameter, loops through the various company Financial Data and metadata to be compared (comparison_data) picks si specific metrics, and compares the metrics of the chosen profile, to the SpaceX profile we defined earlier

def scoring_function(comparison_data):
    scored_tranches = []
    primary_metrics = ["momentum", "volatility", "unlock_to_volume", "market_cap", "price_to_sales", "revenue_growth"]
    fallback_metrics = ["momentum", "volatility", "unlock_to_volume", "market_cap"]
    for data in comparison_data:
        primary_valid = all(
            data[metric][0] is not None and data[metric][1] is not None
            for metric in primary_metrics)
        if primary_valid:
            metrics = primary_metrics
        else:
            fallback_valid = all(
                data[metric][0] is not None and data[metric][1] is not None
                for metric in fallback_metrics)
            if not fallback_valid:
                error_logging("invalid_comparison")
                print("Invalid comparison value, skipping...")
                continue
            metrics = fallback_metrics
        metric_scores = []
        for metric in metrics:
            spacex_value, historical_value = data[metric]
            difference = abs(historical_value - spacex_value)
            scale = (abs(spacex_value) + abs(historical_value)) / 2
            if scale == 0:
                metric_similarity = 1.0
            else:
                normalized_difference = difference / scale
                metric_similarity = 1 / (1 + normalized_difference)
            metric_scores.append(metric_similarity)
        overall_score = sum(metric_scores) / len(metric_scores)
        scored_record = {
            "spacex_tranche": data["spacex_tranche"],
            "historical_ticker": data["historical_ticker"],
            "historical_tranche": data["historical_tranche"],
            "historical_return": data.get("historical_return"),
            "similarity_score": overall_score}
        scored_tranches.append(scored_record)
    return scored_tranches
# This is the pseudo prediction model that actually tells us if the stock is bearish or bullish, I'll likely simply do this using a Bool value, if the function returns False, I'll have an if statement that decides its "Bearish", if the function returns True, I'll have an if statement that decides its "Bullish"
# DISCLAIMER: THIS IS A PSEUDO PREDICTION ALGORITHM. THIS ENGINE IS MEANT SOLELY FOR THE PURPOSE OF DEMONSTRATING TECHNICAL DEPTH AND SHOULD NOT BE USED TO EVALUATE REAL FINANCIAL RISK OR MAKE INVESTMENT DECISIONS

def prediction_function(SPACEX_PROFILE, finished_profiles):
    bullish_evidence = 0
    bearish_evidence = 0
    primary_metrics = ["momentum", "volatility", "unlock_to_volume", "market_cap", "price_to_sales", "revenue_growth"]
    fallback_metrics = ["momentum", "volatility", "unlock_to_volume", "market_cap"]
    for profile in finished_profiles:
        historical_outcome = profile["historical_return"]
        if historical_outcome is None:
            error_logging("empty_historical_outcome")
            print("Empty historical return, cannot run prediction function on this specific value")
            continue
        predictive_influences = []
        for spacex_profile in SPACEX_PROFILE:
            primary_valid = all(
                spacex_profile[metric] is not None and profile[metric] is not None
                for metric in primary_metrics)
            if primary_valid:
                metrics = primary_metrics
            else:
                fallback_valid = all(
                    spacex_profile[metric] is not None and profile[metric] is not None
                    for metric in fallback_metrics)
                if not fallback_valid:
                    continue
                metrics = fallback_metrics
            spacex_distances = []
            for metric in metrics:
                spacex_value = spacex_profile[metric]
                historical_value = profile[metric]
                difference = abs(historical_value - spacex_value)
                scale = (abs(spacex_value) + abs(historical_value)) / 2
                if scale == 0:
                    normalized_distance = 0.0
                else:
                    normalized_distance = difference / scale
                spacex_distances.append(normalized_distance)
            average_distance = sum(spacex_distances) / len(spacex_distances)
            influence_weight = 1 / (1 + average_distance)
            predictive_influences.append(influence_weight)
        if not predictive_influences:
            continue
        combined_influence = sum(predictive_influences) / len(predictive_influences)
        if historical_outcome > 0:
            bullish_evidence += combined_influence
        elif historical_outcome < 0:
            bearish_evidence += combined_influence
    total_evidence = bullish_evidence + bearish_evidence
    if total_evidence == 0:
        return {
            "bullish_percentage": None,
            "bearish_percentage": None,
            "prediction": "Insufficient Data"}
    bullish_percentage = (bullish_evidence / total_evidence) * 100
    bearish_percentage = (bearish_evidence / total_evidence) * 100
    if bullish_percentage > bearish_percentage:
        prediction = "Bullish"
    elif bearish_percentage > bullish_percentage:
        prediction = "Bearish"
    else:
        prediction = "Mixed"
    forecast = {
        "bullish_percentage": bullish_percentage,
        "bearish_percentage": bearish_percentage,
        "prediction": prediction}
    return forecast

# Because the bullish-bearish prediction is separate from the similarity scoring engine, we need a helper function that combines all Financial Data in companies.csv and ipo_metadata.
# We need to then convert those metrics into an entire comparable "universe" containing all ticker Financial Data, then pass through our earlier prediction function
# That universe is the function below

def prediction_historical_universe(comparable_tickers):
    historical_universe = []

    for ticker in comparable_tickers:
        ticker_profiles = analyze_ticker(ticker)
        for profile in ticker_profiles:
            historical_universe.append(profile)
    return historical_universe

# Hardcoding a global variable containing every ticker except SPCX that we will pass through "prediction_historical_universe" so that when we call the function we get a full list of all ticker Financial Data

universal_tickers = ["META", "RKLB", "ASTS", "BABA", ]
# historical_universe_return = prediction_historical_universe(universal_tickers)
# universe = prediction_function(SPACEX_PROFILE, historical_universe_return)

# Next we need to create a clean entry point that ui.py can access

def user_interface_controller(selected_ticker):
    # Storage lists
    similarity_scores = []
    ui_components = []

    selected_ticker_profiles = analyze_ticker(selected_ticker)
    spacex_ticker_comparison = analyze_spacex_data(SPACEX_PROFILE,selected_ticker_profiles)
    scoring_tranche_pairings = scoring_function(spacex_ticker_comparison)

    for scoring in scoring_tranche_pairings:
        score = scoring["similarity_score"]
        similarity_scores.append(score)
    if len(similarity_scores) == 0:
        error_logging("similarity_scores")
        raise ValueError("Invalid Financial Data in user_interface_controller. Cannot complete function")
    else:
        universal_similarity_score = sum(similarity_scores) / len(similarity_scores)
    prediction_label = universe["prediction"]
    bullish_percent = universe["bullish_percentage"]
    bearish_percent = universe["bearish_percentage"]
    ui_component_1 = f"Aggregate Similarity: SpaceX is {universal_similarity_score * 100}% similar to {selected_ticker} across all evaluated lockup-tranche comparisons"
    ui_component_2 = f"Universal Lockup Signal: {prediction_label} | {bullish_percent} Bullish Evidence vs. {bearish_percent} Bearish Evidence. Prediction from weighted engine."
    # UI Component loop

    for pairing in scoring_tranche_pairings:
        dict_tranche = pairing["historical_tranche"]
        dict_ticker = pairing["historical_ticker"]
        dict_score = pairing["similarity_score"]
        dict_spacex_tranche = pairing["spacex_tranche"]
        # String variables that ui.py will see
        ui_component_3 = f"SpaceX Tranche {dict_spacex_tranche} vs {dict_ticker} Tranche {dict_tranche}: {dict_score * 100:.1f}% similarity"

        ui_components.append(ui_component_3)
    result = {
        "ui_components": ui_components,
        "ui_component_1": ui_component_1,
        "ui_component_2": ui_component_2,
    }
    return result

# When we call engine from the ui, we do not want the engine to run immediately upon generation of the ui,

def engine_controller(selected_ticker):
    global companies, lockups, SPACEX_PROFILE, universe # Defines everything we had used before as global in this function, so we don't have undefined variables in the codebase when we move it

    companies = read_companies()
    lockups = read_ipo_lockups()

    spacex_companies_filter = company_filter("SPCX", companies)
    spacex_lockup_filter = lockup_filter("SPCX", lockups)
    spacex_date_window = date_window(spacex_lockup_filter, spacex_companies_filter)

    spacex_avg_volume = average_trading_volume(spacex_date_window)
    spacex_momentum = thirty_day_momentum(spacex_date_window)
    spacex_volatility = volatility(spacex_date_window)
    spacex_ratio = unlock_to_volume_ratio(spacex_date_window, spacex_avg_volume)
    spacex_market_cap = market_cap_metric(spacex_date_window)
    spacex_price_to_sales = price_to_sales(spacex_date_window)
    spacex_revenue_growth = revenue_growth(spacex_date_window, spacex_companies_filter)

    SPACEX_PROFILE = []
    for index, window in enumerate(spacex_date_window):
        spacex_profile = {
            "ticker": "SPCX",
            "tranche": window["lockup"]["tranche"],
            "momentum": spacex_momentum[index],
            "volatility": spacex_volatility[index],
            "unlock_to_volume": spacex_ratio[index],
            "market_cap": spacex_market_cap[index],
            "price_to_sales": spacex_price_to_sales[index],
            "revenue_growth": spacex_revenue_growth[index]
        }
        SPACEX_PROFILE.append(spacex_profile)

    historical_universe_return = prediction_historical_universe(universal_tickers)
    universe = prediction_function(SPACEX_PROFILE, historical_universe_return)

    return user_interface_controller(selected_ticker)
