import datetime
import csv
import statistics
import matplotlib.pyplot as plt

# Reading the IPO Lockup csv will all our metadata and the ticker names
Stocklist = 'data/ipo_metadata.csv'

def read_ipo_lockups():
    with open('data/ipo_metadata.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        lockups = []
        for row in reader:
            lockups.append(row)
    return lockups

read_ipo_lockups()

# Reading the companies csv generated by indigestion

def read_companies():
    with open('data/companies.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        companies = []
        for row in reader:
            companies.append(row)
    return companies

# Functions that called what were returned by the read functions

companies = read_companies()
lockups = read_ipo_lockups()

# Filtering the rows to return all tickers with the same name Ex: "META" into an accessible format allowing us to score them easier

def company_filter(ticker, companies):
    matching_companies = []
    for company in companies:
        if company['ticker'] == ticker:
            matching_companies.append(company)
    return matching_companies

# Same exact thing but instead filtering lockups to make all the metadata in ipo_metadata.csv accessible to be called

def lockup_filter(ticker, lockups):
    matching_lockups = []
    for lockup in lockups:
        if lockup['ticker'] == ticker:
            matching_lockups.append(lockup)
    return matching_lockups

# Filtering the IPO lockup dates to only pull data from the relevant tranches and specific periods for scoring

def date_window(matching_lockups, matching_companies):
    all_windows = []

    sorted_companies = sorted(
        matching_companies,
        key=lambda company: datetime.datetime.strptime(company['date'], "%Y-%m-%d")
    )

    for lockup in matching_lockups:
        lockup_date = lockup['lockup_date']
        lockup_datetime = datetime.datetime.strptime(lockup_date, "%Y-%m-%d")

        date_window_list = []

        for company in sorted_companies:
            company_date = company['date']
            company_datetime = datetime.datetime.strptime(company_date, "%Y-%m-%d")

            if company_datetime < lockup_datetime:
                date_window_list.append(company)

        thirty_day_window = date_window_list[-30:]

        window_record = {
            "lockup": lockup,
            "trading_window": thirty_day_window
        }

        all_windows.append(window_record)

    return all_windows

def thirty_day_momentum(date_windows):
    momentum_results = []

    for window_record in date_windows:
        trading_window = window_record["trading_window"]

        first_close = float(trading_window[0]["close"])
        last_close = float(trading_window[-1]["close"])

        momentum = (last_close / first_close) - 1

        momentum_results.append(momentum)

    return momentum_results

# This is the function we use to calculate the volatility of the stock

# Helper function in order to allow us to print the results
def save_volatility_chart(date_windows, volatility_results):
    tranche_labels = []

    for window_record in date_windows:
        tranche = window_record["lockup"]["tranche"]
        tranche_labels.append(f"Tranche {tranche}")

    ticker = date_windows[0]["lockup"]["ticker"]

    plt.figure(figsize=(8, 5))
    plt.bar(tranche_labels, volatility_results)

    plt.title(f"{ticker} 30-Day Pre-Lockup Volatility")
    plt.xlabel("Lockup Tranche")
    plt.ylabel("Standard Deviation")

    plt.tight_layout()

    file_path = f"data/{ticker}_volatility.png"

    plt.savefig(file_path)
    plt.close()

    return file_path

def volatility(date_window):
    volatility_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        daily_returns = []
        for day_index in range(1, len(trading_window)): # This inner loop is meant to find the exact day-to-day close and previous close. We cannot use basic indexing because volatility needs to compare everything to the day before it
            current_close = float(trading_window[day_index]["close"])
            previous_close = float(trading_window[day_index - 1]["close"])

            daily_return_calculation = current_close / previous_close - 1

            daily_returns.append(daily_return_calculation)
        # End of the inner loop, the purpose was to simply calculate the daily return percentage and add it to daily_returns for each company
        standard_deviation_volatility = statistics.stdev(daily_returns)
        volatility_results.append(standard_deviation_volatility)

    save_volatility_chart(date_window, volatility_results)

    return volatility_results

# This next function is meant to find the daily trading volume for each stock and tranche. This function allows us to calculate shares unlock with average trading volume, allowing us to see how much the shares unlocked affects the trading volume
def average_trading_volume(date_window):
    trading_volume_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        daily_volume = []
        for day_index in range(0, len(trading_window)): # Inner loop is meant to iterate to each individual company day and return the day-to-day results from companies.csv
            day_volume = float(trading_window[day_index]["volume"])
            daily_volume.append(day_volume)
        average_daily_volume = statistics.mean(daily_volume)
        trading_volume_results.append(average_daily_volume)
    return trading_volume_results

# A usable variable that allows us to access the output from average trading volume

def unlock_to_volume_ratio(date_window, avg_volume):
    ratio_results = []
    for index, window_record in enumerate(date_window):
        shares_unlocked = float(window_record["lockup"]["shares_unlocked"])
        matching_average_volume = avg_volume[index]
        u_to_v_ratio = shares_unlocked / matching_average_volume
        ratio_results.append(u_to_v_ratio)
    return ratio_results

# Now we are moving to an outcome, we are not comparing historical return to similarity, we are measuring an outcome determine if the SpaceX stock is bullish or bearish based on how past post-lockup returns happened.
# The question we are trying to answer is "What happened to the stock after its original lockup expiration?"

def historical_return(date_window, filtered_companies):
    historical_results = []

    sorted_companies = sorted(
        filtered_companies,
        key=lambda company: datetime.datetime.strptime(company["date"], "%Y-%m-%d")
    )

    for window_record in date_window:
        lockup_date = window_record["lockup"]["lockup_date"]
        lockup_datetime = datetime.datetime.strptime(lockup_date, "%Y-%m-%d")

        post_lockup_rows = []

        for company in sorted_companies:
            company_datetime = datetime.datetime.strptime(company["date"], "%Y-%m-%d")

            if company_datetime >= lockup_datetime:
                post_lockup_rows.append(company)

        if len(post_lockup_rows) >= 21:
            starting_close = float(post_lockup_rows[0]["close"])
            ending_close = float(post_lockup_rows[20]["close"])

            twenty_day_return = (ending_close / starting_close) - 1
            historical_results.append(twenty_day_return)

        else:
            historical_results.append(None)

    return historical_results

def market_cap_metric(date_window):
    market_cap_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        latest_market_cap = None

        for company in reversed(trading_window):
            if company["market_cap"]:
                latest_market_cap = float(company["market_cap"])
                break

        market_cap_results.append(latest_market_cap)

    return market_cap_results


def price_to_sales(date_window):
    price_to_sales_results = []
    for window_record in date_window:
        trading_window = window_record["trading_window"]
        price_to_sales_ratio = None

        for company in reversed(trading_window):
            if company["market_cap"] and company["revenue"]:
                market_cap = float(company["market_cap"])
                ttm_revenue = float(company["revenue"])

                if ttm_revenue != 0:
                    price_to_sales_ratio = market_cap / ttm_revenue
                break

        price_to_sales_results.append(price_to_sales_ratio)

    return price_to_sales_results

# Function for calculating the company's revenue growth

def revenue_growth(date_window, filtered_companies):
    revenue_growth_results = []
    sorted_companies = sorted(
        filtered_companies,
        key=lambda company: datetime.datetime.strptime(company["date"], "%Y-%m-%d"))
    for window_record in date_window:
        lockup_date = window_record["lockup"]["lockup_date"]
        lockup_datetime = datetime.datetime.strptime(lockup_date, "%Y-%m-%d")
        revenue_updates = []
        previous_revenue = None
        for company in sorted_companies:
            company_datetime = datetime.datetime.strptime(company["date"], "%Y-%m-%d")
            if company_datetime >= lockup_datetime:
                break
            if company["revenue"] and company["period"] == "TTM":
                current_revenue = float(company["revenue"])
                if current_revenue != previous_revenue:
                    revenue_updates.append(current_revenue)
                    previous_revenue = current_revenue
        if len(revenue_updates) >= 5:
            current_ttm_revenue = revenue_updates[-1]
            prior_year_ttm_revenue = revenue_updates[-5]
            if prior_year_ttm_revenue != 0:
                growth = (current_ttm_revenue / prior_year_ttm_revenue) - 1
                revenue_growth_results.append(growth)
            else:
                revenue_growth_results.append(None)
        else:
            revenue_growth_results.append(None)
    return revenue_growth_results

# This defines the profile for each of the tickers that we will use to score against SpaceX. The profile includes everything that we will use to compare our companies

def profile_combination_helper(date_windows, momentum_results, volatility_results, avg_volume, ratio_results, historical_results, market_cap_metrics, price_to_sale, revenue_growth_function):
    finished_profiles = []
    for index, window in enumerate(date_windows):
        tranche_profile = {
            "ticker": window["lockup"]["ticker"],
            "tranche": window["lockup"]["tranche"],
            "lockup_date": window["lockup"]["lockup_date"],
            "shares_unlocked": window["lockup"]["shares_unlocked"],
            "momentum": momentum_results[index],
            "volatility": volatility_results[index],
            "average_volume": avg_volume[index],
            "unlock_to_volume": ratio_results[index],
            "historical_return": historical_results[index],
            "market_cap": market_cap_metrics[index],
            "price_to_sales": price_to_sale[index],
            "revenue_growth": revenue_growth_function[index]
        }
        finished_profiles.append(tranche_profile)
    return finished_profiles

# Flow control function, meant to control the sequence of all of our data gathering and calculation functions

def analyze_ticker(ticker):
    filtered_lockups = lockup_filter(ticker, lockups)
    filtered_companies = company_filter(ticker, companies)
    date_windows = date_window(filtered_lockups, filtered_companies)
    momentum_results = thirty_day_momentum(date_windows)
    volatility_results = volatility(date_windows)
    avg_volume = average_trading_volume(date_windows)
    ratio_results = unlock_to_volume_ratio(date_windows, avg_volume)
    historical_results = historical_return(date_windows, filtered_companies)
    market_cap_metrics = market_cap_metric(date_windows)
    price_to_sale = price_to_sales(date_windows)
    revenue_growth_function = revenue_growth(date_windows, filtered_companies)
    helper = profile_combination_helper(date_windows, momentum_results, volatility_results, avg_volume, ratio_results, historical_results, market_cap_metrics, price_to_sale, revenue_growth_function)
    return (helper, date_windows, momentum_results, volatility_results, avg_volume, ratio_results,historical_results, price_to_sale, revenue_growth_function, market_cap_metrics)